/* Zelda PC Engine VCE Palettes - Generated by convert_zelda.py */
#ifndef _ZELDA_PALETTES_H
#define _ZELDA_PALETTES_H


// Set Palettes for Title Screen (Image 1)
void set_title_palettes(void)
{
    // Backdrop / Peach Sky: (7, 5, 5)
    // BG Palette 0: Cliffs and Text (Peach, Black, Dark Gray, Light Gray)
    set_color_rgb(0, 7, 5, 5); // Backdrop Peach Sky
    set_color_rgb(1, 0, 0, 0); // Black Text
    set_color_rgb(2, 3, 3, 3); // Dark Gray Cliff
    set_color_rgb(3, 5, 5, 5); // Light Gray Cliff Highlight

    // BG Palette 1: Triforce and ZELDA Lettering (Peach, Dark Gold, Bright Gold, Black)
    set_color_rgb(16, 7, 5, 5); // Peach Sky
    set_color_rgb(17, 5, 3, 0); // Dark Gold / Brown
    set_color_rgb(18, 7, 6, 1); // Bright Gold / Yellow Highlight
    set_color_rgb(19, 0, 0, 0); // Black Lettering Border

    // BG Palette 2: Leaf Wreath Border (Peach, Dark Green, Bright Green, Yellow-Green)
    set_color_rgb(32, 7, 5, 5); // Peach Sky
    set_color_rgb(33, 0, 3, 0); // Dark Forest Green
    set_color_rgb(34, 1, 6, 1); // Bright Green
    set_color_rgb(35, 5, 7, 1); // Yellow-Green Leaf Highlight

    // BG Palette 3: Waterfall and Sword (Peach, White, Pale Mint, Aqua Blue)
    set_color_rgb(48, 7, 5, 5); // Peach Sky
    set_color_rgb(49, 7, 7, 7); // Pure White Foam & Sword Blade
    set_color_rgb(50, 4, 7, 6); // Pale Mint Water
    set_color_rgb(51, 1, 4, 6); // Aqua Blue Water Spray

    // Sprite Palette 0 (VCE subpalette 16): Sparkle Glint / Highlights
    set_color_rgb(256, 0, 0, 0); // Transparent
    set_color_rgb(257, 7, 7, 7); // Pure White
    set_color_rgb(258, 4, 7, 6); // Pale Mint
    set_color_rgb(259, 7, 4, 1); // Orange / Gold

    // Sprite Palette 1 (VCE subpalette 17): Sword Hilt (Gold)
    set_color_rgb(272, 0, 0, 0); // Transparent
    set_color_rgb(273, 5, 3, 0); // Dark Gold / Brown
    set_color_rgb(274, 7, 6, 1); // Bright Gold
    set_color_rgb(275, 0, 0, 0); // Black

    // Sprite Palette 2 (VCE subpalette 18): Leaf Wreath Corners (matches BG Pal 2)
    set_color_rgb(288, 0, 0, 0); // Transparent
    set_color_rgb(289, 0, 3, 0); // Dark Forest Green
    set_color_rgb(290, 1, 6, 1); // Bright Green
    set_color_rgb(291, 5, 7, 1); // Yellow-Green Leaf Highlight

    // Sprite Palette 3 (VCE subpalette 19): Waterfall Waves & Crest (matches BG Pal 3)
    set_color_rgb(304, 0, 0, 0); // Transparent
    set_color_rgb(305, 7, 7, 7); // Pure White Foam
    set_color_rgb(306, 4, 7, 6); // Pale Mint Water
    set_color_rgb(307, 1, 4, 6); // Aqua Blue Water Spray
}

// Set Palettes for Story Prologue Scroll Screen
void set_story_palettes(void)
{
    // BG Palette 0: Pure White text on Black
    set_color_rgb(0, 0, 0, 0);
    set_color_rgb(1, 7, 7, 7);
    set_color_rgb(2, 7, 7, 7);
    set_color_rgb(3, 7, 7, 7);

    // BG Palette 1: Light Blue text on Black
    set_color_rgb(16, 0, 0, 0);
    set_color_rgb(17, 2, 4, 7);
    set_color_rgb(18, 7, 7, 7);
    set_color_rgb(19, 7, 7, 7);

    // BG Palette 2: Red text & title on Black
    set_color_rgb(32, 0, 0, 0);
    set_color_rgb(33, 6, 1, 1);
    set_color_rgb(34, 7, 7, 7);
    set_color_rgb(35, 7, 7, 7);

    // BG Palette 3: Green pillars and frame borders
    set_color_rgb(48, 0, 0, 0);
    set_color_rgb(49, 3, 7, 2);
    set_color_rgb(50, 1, 6, 1);
    set_color_rgb(51, 0, 3, 0);
}

// Set Palettes for All of Treasures Showcase
void set_treasures_palettes(void)
{
    // BG Palettes same as story
    set_story_palettes();

    // Sprite Palette 0 (VCE 16): Green, Yellow/Gold, Brown
    set_color_rgb(256, 0, 0, 0); // Transparent
    set_color_rgb(257, 0, 5, 0); // Green
    set_color_rgb(258, 7, 6, 4); // Yellow/Beige
    set_color_rgb(259, 6, 2, 0); // Brown/Orange

    // Sprite Palette 1 (VCE 17): Dark Blue, Light Blue, White
    set_color_rgb(272, 0, 0, 0); // Transparent
    set_color_rgb(273, 0, 0, 5); // Dark Blue
    set_color_rgb(274, 2, 4, 7); // Light Blue
    set_color_rgb(275, 7, 7, 7); // White

    // Sprite Palette 2 (VCE 18): Crimson Red, Peach, White
    set_color_rgb(288, 0, 0, 0); // Transparent
    set_color_rgb(289, 6, 0, 2); // Crimson Red
    set_color_rgb(290, 7, 4, 2); // Peach/Orange
    set_color_rgb(291, 7, 7, 7); // White

    // Sprite Palette 3 (VCE 19): Dark Green, Green, Light Green
    set_color_rgb(304, 0, 0, 0); // Transparent
    set_color_rgb(305, 0, 3, 0); // Dark Green
    set_color_rgb(306, 0, 5, 2); // Green
    set_color_rgb(307, 2, 7, 4); // Light Green
}

// Set Palettes for File Select Screen (Mode 1, Image 2)
void set_select_palettes(void)
{
    // BG Palette 0: White text on Black background
    set_color_rgb(0, 0, 0, 0); // Black background
    set_color_rgb(1, 7, 7, 7); // Pure White text
    set_color_rgb(2, 4, 4, 4); // Gray
    set_color_rgb(3, 0, 0, 0); // Black

    // BG Palette 1: Royal Blue Box Frame
    set_color_rgb(16, 0, 0, 0); // Black
    set_color_rgb(17, 1, 2, 7); // Royal Blue
    set_color_rgb(18, 2, 5, 7); // Azure / Bright Blue
    set_color_rgb(19, 7, 7, 7); // White Highlight

    // BG Palette 2: Life Hearts (Red)
    set_color_rgb(32, 0, 0, 0); // Black
    set_color_rgb(33, 7, 1, 1); // Bright Crimson Red
    set_color_rgb(34, 4, 0, 0); // Dark Red
    set_color_rgb(35, 7, 7, 7); // White

    // Sprite Palette 0 (VCE subpalette 16): Link Save Slot Icon
    set_color_rgb(256, 0, 0, 0); // Transparent
    set_color_rgb(257, 1, 6, 1); // Green Tunic & Cap
    set_color_rgb(258, 7, 6, 4); // Skin Tone / Peach
    set_color_rgb(259, 5, 2, 0); // Brown Shield & Belt

    // Sprite Palette 1 (VCE subpalette 17): Heart Cursor
    set_color_rgb(272, 0, 0, 0); // Transparent
    set_color_rgb(273, 7, 1, 1); // Bright Crimson Red
    set_color_rgb(274, 4, 0, 0); // Dark Crimson Red
    set_color_rgb(275, 7, 7, 7); // White
}

// Set Palettes for In-Game Overworld and Caves (matching authentic NES palettes)
// Set Palettes for Underworld (Levels 1..9)
void set_underworld_palettes(unsigned char level)
{
    // BG Palette 0: Level 1 Turquoise / Teal Wall & Floor (NES 0x0C, 0x1C, 0x2C)
    set_color_rgb(0, 0, 0, 0); // Black
    set_color_rgb(1, 0, 3, 4); // Dark Teal
    set_color_rgb(2, 0, 5, 5); // Cyan / Teal
    set_color_rgb(3, 4, 7, 7); // Light Teal / White

    // BG Palette 1: HUD White Text & Minimap Grey
    set_color_rgb(16, 0, 0, 0);
    set_color_rgb(17, 7, 7, 7);
    set_color_rgb(18, 2, 2, 2);
    set_color_rgb(19, 7, 7, 7);

    // BG Palette 2: Blue Item Boxes 'B' and 'A'
    set_color_rgb(32, 0, 0, 0);
    set_color_rgb(33, 7, 7, 7);
    set_color_rgb(34, 2, 4, 7);
    set_color_rgb(35, 1, 2, 7);

    // BG Palette 3: HUD Red '-LIFE-' & Hearts
    set_color_rgb(48, 0, 0, 0);
    set_color_rgb(49, 6, 1, 1);
    set_color_rgb(50, 3, 0, 0);
    set_color_rgb(51, 7, 5, 5); // NES Pink ($26) for half-heart right side

    // BG Palette 4: Orange Rupee & Key Icons
    set_color_rgb(64, 0, 0, 0);
    set_color_rgb(65, 7, 7, 7);
    set_color_rgb(66, 6, 4, 1);
    set_color_rgb(67, 4, 2, 0);

    // BG Palette 5: Minimap Green Locator Dot
    set_color_rgb(80, 0, 0, 0);
    set_color_rgb(81, 1, 6, 1);
    set_color_rgb(82, 2, 2, 2);
    set_color_rgb(83, 7, 7, 7);

    // Sprite Palette 0 (subpal 16): Link
    set_color_rgb(256, 0, 0, 0);
    set_color_rgb(257, 0, 4, 0);
    set_color_rgb(258, 6, 5, 4);
    set_color_rgb(259, 4, 2, 0);

    // Sprite Palette 1 (subpal 17): Red Monster / Stalfos / Flame
    set_color_rgb(272, 0, 0, 0);
    set_color_rgb(273, 6, 1, 1);
    set_color_rgb(274, 7, 4, 1);
    set_color_rgb(275, 7, 7, 7);

    // Sprite Palette 2 (subpal 18): Heart Cursor / Red Link / Items
    set_color_rgb(288, 0, 0, 0);
    set_color_rgb(289, 6, 1, 1);
    set_color_rgb(290, 3, 0, 0);
    set_color_rgb(291, 7, 7, 7);

    // Sprite Palette 3 (subpal 19): Wooden Sword
    set_color_rgb(304, 0, 0, 0);
    set_color_rgb(305, 0, 5, 0); // Green Guard
    set_color_rgb(306, 6, 4, 1); // Tan Grip
    set_color_rgb(307, 4, 2, 0); // Brown Wood Blade

    // Sprite Palette 4 (subpal 20): Blue Monster / Blue Keese / Goriya
    set_color_rgb(320, 0, 0, 0);
    set_color_rgb(321, 1, 3, 7);
    set_color_rgb(322, 2, 5, 7);
    set_color_rgb(323, 7, 7, 7);
}

void set_game_palettes(void)
{
    // BG Palette 0: Overworld Green Forest (NES pal_sel 2)
    set_color_rgb(0, 0, 0, 0); // Black Outline / Cave Mouth / Empty Space
    set_color_rgb(1, 0, 3, 0); // Green Tree Foliage (NES 0x1A)
    set_color_rgb(2, 6, 6, 3); // Warm Sand Tan Ground (NES 0x37)
    set_color_rgb(3, 1, 2, 6); // Authentic Water Blue (NES 0x12)

    // BG Palette 1: HUD White Text & Minimap Grey (and Cave Text)
    set_color_rgb(16, 0, 0, 0); // Black HUD Background
    set_color_rgb(17, 7, 7, 7); // Pure White Text ('X', '0', Dialogue)
    set_color_rgb(18, 2, 2, 2); // Minimap Grey (Tile 0xF5)
    set_color_rgb(19, 7, 7, 7); // White

    // BG Palette 2: Blue Item Boxes 'B' and 'A'
    set_color_rgb(32, 0, 0, 0); // Black Background
    set_color_rgb(33, 7, 7, 7); // White Letters ('B' and 'A')
    set_color_rgb(34, 2, 4, 7); // Azure / Bright Blue
    set_color_rgb(35, 1, 2, 7); // Royal Blue Box Borders (Tiles 69..6E)

    // BG Palette 3: HUD Red '-LIFE-' & Hearts
    set_color_rgb(48, 0, 0, 0); // Black Background
    set_color_rgb(49, 6, 1, 1); // Crimson Red ('-LIFE-' and hearts 0xF2)
    set_color_rgb(50, 3, 0, 0); // Dark Red
    set_color_rgb(51, 7, 5, 5); // NES Pink ($26) for half-heart right side

    // BG Palette 4: Orange Rupee & Key Icons
    set_color_rgb(64, 0, 0, 0); // Black
    set_color_rgb(65, 7, 7, 7); // White Highlight
    set_color_rgb(66, 6, 4, 1); // Orange / Gold (Rupee 0xF7, Key 0xF9)
    set_color_rgb(67, 4, 2, 0); // Dark Gold

    // BG Palette 5: Minimap Green Locator Dot (Tile 0xFE)
    set_color_rgb(80, 0, 0, 0); // Black
    set_color_rgb(81, 1, 6, 1); // Bright Green Locator Dot (pixel 1)
    set_color_rgb(82, 2, 2, 2); // Minimap Grey (pixel 2)
    set_color_rgb(83, 7, 7, 7); // White

    // BG Palette 6: Cliff Rocks / Mountains (NES pal_sel 1)
    set_color_rgb(96, 0, 0, 0); // Black Outline
    set_color_rgb(97, 3, 2, 0); // Brown Mountains (NES 0x17)
    set_color_rgb(98, 6, 6, 3); // Warm Sand Tan Ground (NES 0x37)
    set_color_rgb(99, 1, 2, 6); // Authentic Water Blue (NES 0x12)

    // BG Palette 7: Brown Trees / Coast (NES pal_sel 3)
    set_color_rgb(112, 0, 0, 0); // Black Outline
    set_color_rgb(113, 3, 2, 0); // Brown Tree Foliage (NES 0x17)
    set_color_rgb(114, 6, 6, 3); // Warm Sand Tan Ground (NES 0x37)
    set_color_rgb(115, 1, 2, 6); // Authentic Water Blue (NES 0x12)

    // BG Palette 8: Graveyard / White / Gray (NES pal_sel 0)
    set_color_rgb(128, 0, 0, 0); // Black Outline
    set_color_rgb(129, 5, 5, 5); // White / Light Gray
    set_color_rgb(130, 6, 5, 4); // Sand Tan Ground
    set_color_rgb(131, 1, 2, 6); // Authentic Water Blue (NES 0x12)

    // BG Palette 9: Cave Walls (Brown Rock Walls matching Image 2)
    set_color_rgb(144, 0, 0, 0); // Black
    set_color_rgb(145, 4, 1, 0); // Dark Red/Brown
    set_color_rgb(146, 6, 4, 1); // Light Brown
    set_color_rgb(147, 7, 6, 5); // Light Buff

    // Sprite Palette 0 (VCE subpalette 16): Link
    set_color_rgb(256, 0, 0, 0); // Transparent
    set_color_rgb(257, 0, 4, 0); // Link Green Tunic & Cap
    set_color_rgb(258, 6, 5, 4); // Skin Tone / Peach
    set_color_rgb(259, 4, 2, 0); // Brown Belt / Shield

    // Sprite Palette 1 (VCE subpalette 17): Red Monster / Old Man / Fire
    set_color_rgb(272, 0, 0, 0); // Transparent
    set_color_rgb(273, 6, 1, 1); // Color 1: Crimson Red (Monster Body, Old Man Robe, Fire outer flame)
    set_color_rgb(274, 7, 4, 1); // Color 2: Orange / Peach (Monster Eyes/Iris, Old Man Skin, Fire body)
    set_color_rgb(275, 7, 7, 7); // Color 3: Pure White (Monster Belly/Snout, Old Man Beard, Fire core)

    // Sprite Palette 2 (VCE subpalette 18): Heart Cursor / Red Link
    set_color_rgb(288, 0, 0, 0); // Transparent
    set_color_rgb(289, 6, 1, 1); // Crimson Red
    set_color_rgb(290, 3, 0, 0); // Dark Crimson Red
    set_color_rgb(291, 7, 7, 7); // Pure White

    // Sprite Palette 3 (VCE subpalette 19): Wooden Sword
    set_color_rgb(304, 0, 0, 0); // Transparent
    set_color_rgb(305, 0, 5, 0); // Green Guard
    set_color_rgb(306, 6, 4, 1); // Tan Grip
    set_color_rgb(307, 4, 2, 0); // Brown Wood Blade

    // Sprite Palette 4 (VCE subpalette 20): Blue Monster
    set_color_rgb(320, 0, 0, 0); // Transparent
    set_color_rgb(321, 1, 3, 7); // Color 1: Royal Blue Body
    set_color_rgb(322, 2, 5, 7); // Color 2: Cyan / Light Blue Eyes
    set_color_rgb(323, 7, 7, 7); // Color 3: Pure White Belly & Snout
}

#endif
